steps:
- pwsh: cargo install cross --git https://github.com/cross-rs/cross --rev c87a52a60dbcde069714a8d2ed51570e7fc23cf9
  displayName: ğŸ› ï¸ install cross

- pwsh: cross build -r --target=aarch64-linux-android
  displayName: ğŸ› ï¸ build android-arm64
  workingDirectory: src/nerdbank-zcash-rust

- pwsh: cross build -r --target=x86_64-linux-android
  displayName: ğŸ› ï¸ build android-x64
  workingDirectory: src/nerdbank-zcash-rust

- pwsh: cross build -r --target=aarch64-unknown-linux-gnu
  displayName: ğŸ› ï¸ build linux-arm64
  workingDirectory: src/nerdbank-zcash-rust

- powershell: azure-pipelines/artifacts/_pipelines.ps1 -ArtifactNameSuffix "-$(Agent.JobName)" -Verbose
  failOnStderr: true
  displayName: ğŸ“¢ Publish artifacts
  condition: succeededOrFailed()
